import Head from 'next/head'
import HomePage from '../components/HomePage'

export default () => {
  return (
    <div>
      <Head>
        <title>Homi Test App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="img/logo.png" />
      </Head>
      <HomePage />
    </div>
  )
}
